rabbit:
  image: "rabbitmq:3-management"
  environment:
    RABBITMQ_DEFAULT_USER: "user"
    RABBITMQ_DEFAULT_PASS: "pass"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - 15672:15672
    - 5672:5672

couchbase_node1:
  image: couchbase
  ports:
    - 8091:8091
    - 8092:8092
    - 8093:8093
    - 11210:11210

#db-client_node1:
#  build: .
#  ports:
#  - 8080:8080
#  links:
#    - rabbit
#    - couchbase_node1